### PR TITLE
Add shell completion automatically to `rstuf`

### PR DESCRIPTION
**Pull request by KAUTH**
Test the CLI: `pip install -e .`

### CODE REVIEW

**Comment by kairoaraujo** [comment]
Isn't required in that case to have it in the `pyproject.toml`?

**Comment by KAUTH** [comment]
> Isn't required in that case to have it in the pyproject.toml?

Yes, I forgot to add it there, thanks!

**Comment by kairoaraujo** [comment]
Not sure why, it doesn't work on my terminal (ksh) 😞

**Comment by KAUTH** [comment]
> I don't know why, but after I install rstuf cli with `pip install -e .` still the terminal doesn't suggest autocomplete options for rstuf.
I am using `zsh`.

- Can you run on you shell: `echo $SHELL`? If it's not `zsh` it's probably because `bash` is set to the default shell.
- In any case, I think there's an easy fix for this. I pushed the change

**Comment by MVrachev** [comment]
> * Can you run on your shell: `echo $SHELL`? If it's not `zsh` it's probably because `bash` is set to the default shell.

```
(.env) ➜  cli [17:47]:  echo $SHELL
/bin/zsh
```

> * In any case, I think there's an easy fix for this. I pushed the change, can you retry?

I tried it again, but sadly it doesn't work.
When you have time we can debug this together.

**Review by kairoaraujo — APPROVED** [review]

**Pull request merged**
