### PR TITLE
Add tests for ceremony edge cases & improve type annotations

### PR DESCRIPTION
**Pull request by MVrachev**
# Description

Add:  
- test we cannot add online key as one of root keys
- requirement that threshold > 2 & add test for that
- test that expiration days must be a positive number

Additionally, improve type annotations in a few places
and move ceremony tests input inside conftest to be reused.

Related to #533

# Additional requirements
- [x] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

# Code of Conduct
By submitting this PR, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.rst).

- [x] I agree to follow this project's Code of Conduct

### CODE REVIEW

**Comment by MVrachev** [comment]
Not sure how this not covered line: https://app.codecov.io/gh/repository-service-tuf/repository-service-tuf-cli/pull/607/blob/repository_service_tuf/helpers/tuf.py#L272 is part of my pr, but will check if I can do something about it.

**Comment by MVrachev** [comment]
I decided to just ignore it as it's part of the old md update which will be soon refactored.

**Review by kairoaraujo — APPROVED** [review]

**Comment by MVrachev** [comment]
FT fix is required before merging this pr.
Have a look at: https://github.com/repository-service-tuf/repository-service-tuf/pull/742

**Review by lukpueh — CHANGES_REQUESTED** [review]
This looks good. I have one inline comment, which should be addressed, and two high level comments, which aren't blockers: 

Generally, I think it's not feasible to test all code branches of the cli tool. Maybe it would be enough to just test this feature on the related helper?

If you do test the ceremony command, I recommend to store the complete list of inputs separately for each invocation, even if there is some redundancy.  Re-using some parts (e.g input_step1, input_step3) and patching others (input_step2) makes the test a bit harder to read.

**Comment by MVrachev** [comment]
> This looks good. I have one inline comment, which should be addressed, and two high level comments, which aren't blockers:
> 
> Generally, I think it's not feasible to test all code branches of the cli tool. Maybe it would be enough to just test this feature on the related helper?

Well, that's a discussion worth having.
I am okay with having helper-specific tests instead of full-flow tests for those cases specific to the helpers.
For example, for threshold, we could test the helper itself only.
Still, given that the test is there and working I won't change it now.

> If you do test the ceremony command, I recommend to store the complete list of inputs separately for each invocation, even if there is some redundancy. Re-using some parts (e.g input_step1, input_step3) and patching others (input_step2) makes the test a bit harder to read.

I disagree. I prefer reading what is changed as to have all of the inputs there and wonder are there any changes in any of the steps.
When you change only for example `input2`, then you know that the change is ONLY related to the root keys configuration.

**Comment by MVrachev** [comment]
Rebased on top of main.
The only new/changed commit is the last one addressing @lukpueh comment.

**Review by lukpueh — APPROVED** [review]

**Comment by MVrachev** [comment]
Again, we need to have https://github.com/repository-service-tuf/repository-service-tuf/pull/742 merged, before ft tests pass here.

**Review by kairoaraujo — APPROVED** [review]

**Pull request merged**
