### PR TITLE
feat: Custom Delegation roles command line

### PR DESCRIPTION
**Pull request by kairoaraujo**
# Description

Add a feature to a user as admin to use Custom Delegations
- [x] Add support to choose to use Custom Delegations on Bootstrap
- [x] Add support to be able to sign a custom delegation
- [x] Add support to create new Custom Delegations when RSTUF is running
- [x] Add support to delete Custom Delegation

TODO:
- [ ] Add support to update Custom Delegation
- [ ] Add support to send new, update, and delete delegations  
- [ ] ~unit tests~ (We will do it in another iteration)

# Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)

# Additional requirements
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

# Code of Conduct
By submitting this PR, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.rst).

- [x] I agree to follow this project's Code of Conduct

### CODE REVIEW

**Review by MVrachev — COMMENTED** [review]
I realized you either decide to use the online key in your custom delegation or you are required to add 2 PEM/Sisgstore keys.
There is no middle ground to allow 1 online key and one PEM/Sigstore key.

**Comment by kairoaraujo** [comment]
> I realized you either decide to use the online key in your custom delegation or you are required to add 2 PEM/Sisgstore keys.
> 
> There is no middle ground to allow 1 online key and one PEM/Sigstore key.

You can if you explicitly declare the online key information while `Add Key`.

Building it in a nice flow in CLI is also possible. I don't see is a must to have.

**Review by MVrachev — COMMENTED** [review]
I was not able to sign a custom target delegation with `rstuf admin metadata sign` when it was missing a signature.

**Review by MVrachev — APPROVED** [review]
I am ready to approve.
There is a bug I mentioned in a comment, but it seems related to API.

The review wasn't fully detailed it was hands-on and high-level review.

Which should we first accept: this pr or https://github.com/repository-service-tuf/repository-service-tuf/pull/817#pullrequestreview-2307487909

**Review by MVrachev — APPROVED** [review]

**Pull request merged**
