### PR TITLE
fix: Email Validation for SigStore identity

### LINKED ISSUE #671: Bug: Verify if the Sigstore `identity` is an email
### What happened?

While using RSTUF CLI, we don't verify if the given identity is an email address or, at least, if it is empty.
Screenshot 2024-08-18 at 20 26 09

### What steps did you take?

Screenshot 2024-08-18 at 20 26 09

### What behavior did you expect?

Please don't accept empty entries or, even better, if the identity isn't in an email format.

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mukulbindal**
# Description

Added Email validation for sigstore identity. It will validate whether the identity input by user is email or not

Fixes #671 

# Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)

# Additional requirements
- [x] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

# Code of Conduct
By submitting this PR, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.rst).

- [x] I agree to follow this project's Code of Conduct

### CODE REVIEW

**Comment by mukulbindal** [comment]
Hi @kairoaraujo, I have reformatted the files. However I see email-validator is not a new library, it's already present in `requirements.txt` as well as `requirements-dev.txt`, hence I didn't add it again. Kindly correct me if I am wrong.

**Comment by mukulbindal** [comment]
Hi @kairoaraujo Apologies for the test case error. It was working fine in my local machine for both python 3.10 and 3.11 as well. I am not sure what is wrong here. So I have mocked the method that is failing. Please bear with me as I am new to these awesome automations.

**Comment by kairoaraujo** [comment]
> Hi @kairoaraujo Apologies for the test case error. It was working fine in my local machine for both python 3.10 and 3.11 as well. I am not sure what is wrong here. So I have mocked the method that is failing. Please bear with me as I am new to these awesome automations.

@mukulbindal,

There is no need to apologize. You have done great work here.
I left some easy comments to fix :)

**Review by kairoaraujo — APPROVED** [review]

**Comment by kairoaraujo** [comment]
@mukulbindal,

Thank you for your contribution! 🙇

**Comment by mukulbindal** [comment]
@kairoaraujo Thank you for assigning me and guiding me :)

**Pull request merged**
