### PR TITLE
Fix bugs in `artifact add` and improve UX

### PR DESCRIPTION
**Pull request by kairoaraujo**
# Description

- Fix bug related the giving the RSTUF API Server (``--api-server``)
- Makes the user experience with ``--path`` and `filepaht` simpler and the output, see the cases below

Using a `rstuf.yaml`

```shell
> rstuf -c rstuf.yaml artifact add ~/tuf_metadata.tar
Artifact Addition status: ACCEPTED (94c234877b124bc5a747a9c4e0cb4761)
Successfully submitted task with a payload of:
{
  "targets": [
    {
      "info": {
        "length": 106956800,
        "hashes": {
          "blake2b-256": "597b97e43e445ecd06dfb8436b19e2ae6cfa137dd66523b9a022989355bde3dc"
        },
        "custom": null
      },
      "path": "tuf_metadata.tar"
    }
  ],
  "add_task_id_to_custom": false,
  "publish_targets": true
}

RSTUF task ID (use to check its status) is: 94c234877b124bc5a747a9c4e0cb4761
```

Using the `--path` and `--api-server`

```shell
> rstuf artifact add ~/tuf_metadata.tar --path tuf/files/ --api-server http://localhost
Artifact Addition status: ACCEPTED (1402d4b980794de98c0f7f99d0787cad)
Successfully submitted task with a payload of:
{
  "targets": [
    {
      "info": {
        "length": 106956800,
        "hashes": {
          "blake2b-256": "597b97e43e445ecd06dfb8436b19e2ae6cfa137dd66523b9a022989355bde3dc"
        },
        "custom": null
      },
      "path": "tuf/files/tuf_metadata.tar"
    }
  ],
  "add_task_id_to_custom": false,
  "publish_targets": true
}

RSTUF task ID (use to check its status) is: 1402d4b980794de98c0f7f99d0787cad
```

Fixes #(issue)

# Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)

# Additional requirements
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

# Code of Conduct
By submitting this PR, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.rst).

- [x] I agree to follow this project's Code of Conduct

### CODE REVIEW

**Comment by MVrachev** [comment]
I am little confused with this behavior: 
`rstuf -c rstuf.yaml artifact add ~/tuf_metadata.tar`
will equal to a path `"path": "tuf_metadata.tar"`
I will think it will equal to the home directory and then `tuf_metadata.tar` like `mvrachev/tuf_metadata.tar`.
And then I am not sure what should happen here `rstuf artifact add ~/tuf_metadata.tar --path tuf/files/ --api-server http://localhost`.
Shouldn't the required argument for `rstuf artifact add` be only the name of the file without any slashes and `~` signgs?

**Comment by kairoaraujo** [comment]
> I am little confused with this behavior: `rstuf -c rstuf.yaml artifact add ~/tuf_metadata.tar` will equal to a path `"path": "tuf_metadata.tar"` I will think it will equal to the home directory and then `tuf_metadata.tar` like `mvrachev/tuf_metadata.tar`. And then I am not sure what should happen here `rstuf artifact add ~/tuf_metadata.tar --path tuf/files/ --api-server http://localhost`. Shouldn't the required argument for `rstuf artifact add` be only the name of the file without any slashes and `~` signgs?

[Please check the examples above](https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/441#issue-1974548985)

Without a `--path`, it just uses the file. It ignores the directories/subdirectories.
The flag `--path` is intended to add a path to the file you want to add.

**Comment by MVrachev** [comment]
> > I am little confused with this behavior: `rstuf -c rstuf.yaml artifact add ~/tuf_metadata.tar` will equal to a path `"path": "tuf_metadata.tar"` I will think it will equal to the home directory and then `tuf_metadata.tar` like `mvrachev/tuf_metadata.tar`. And then I am not sure what should happen here `rstuf artifact add ~/tuf_metadata.tar --path tuf/files/ --api-server http://localhost`. Shouldn't the required argument for `rstuf artifact add` be only the name of the file without any slashes and `~` signgs?
> 
> [Please check the examples above](https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/441#issue-1974548985)
> 
> Without a `--path`, it just uses the file. It ignores the directories/subdirectories. The flag `--path` is intended to add a path to the file you want to add.


It was a bit confusing for me why we have two arguments [filepath](https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/06c23228ffc031da32af08cbc1e84bc94bb13a4a/repository_service_tuf/cli/artifact/add.py#L15) required and [path](https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/06c23228ffc031da32af08cbc1e84bc94bb13a4a/repository_service_tuf/cli/artifact/add.py#L26) optional.
I would suggest improving this pr by renaming the `filepath` argument to `localpath` for example and add a short description. Those two names `filepath` and `path` are just too familiar without explaining much.

**Comment by kairoaraujo** [comment]
> It was a bit confusing for me why we have two arguments [filepath](https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/06c23228ffc031da32af08cbc1e84bc94bb13a4a/repository_service_tuf/cli/artifact/add.py#L15) required and [path](https://github.com/repository-service-tuf/repository-service-tuf-cli/blob/06c23228ffc031da32af08cbc1e84bc94bb13a4a/repository_service_tuf/cli/artifact/add.py#L26) optional. I would suggest improving this pr by renaming the `filepath` argument to `localpath` for example and add a short description. Those two names `filepath` and `path` are just too familiar without explaining much.

Why it is confusing: it is not a parameter but an argument.

```
❯ rstuf artifact add -h
                                                                                                                
 Usage: rstuf artifact add [OPTIONS] FILEPATH                                                                   
                                                                                                                
 Add artifacts to the TUF metadata.                                                                             
 A POST /api/v1/artifacts/ request to the RSTUF API service is carried out, where: - file info is discovered    
 and added to the request payload. The blake2b-256 cryptographic hash function is used to hash the file. -      
 `custom` key of the payload is an empty object - `path` key of the payload is defined by the user              
                                                                                                                
╭─ Options ────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ *  --path  -p  TEXT  A custom path (`TARGETPATH`) for the file, defined in the metadata. [required]          │
│    --help  -h        Show this message and exit.                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
`

**Review by MVrachev — APPROVED** [review]

**Review by MVrachev — APPROVED** [review]

**Review by MVrachev — APPROVED** [review]

**Review by MVrachev — APPROVED** [review]

**Pull request merged**
