### PR TITLE
Improve pre-commit update workflow

### PR DESCRIPTION
**Pull request by KAUTH**
# Description

In the pre-commit update workflow we check
if there are any updates before running the
tests.
Running the current tests can take up to
4 minutes on the GH runners. By checking
if there are any changes to pre-commit
we can conditionally run the tests and
save some GH workflow run time.

# Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)

# Additional requirements
- [ ] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

# Code of Conduct
By submitting this PR, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.rst).

- [x] I agree to follow this project's Code of Conduct

### CODE REVIEW

**Review by MVrachev — APPROVED** [review]
Seems a reasonable optimizaiton.
@kairoaraujo any thoughts?

**Review by MVrachev — APPROVED** [review]

**Comment by KAUTH** [comment]
@MVrachev how do we trigger the two last tests (DAS, Signed)? They are supposed to be triggered by the approved status

**Review by kairoaraujo — APPROVED** [review]

**Comment by kairoaraujo** [comment]
> @MVrachev/@kairoaraujo how do we trigger the two last tests (DAS, Signed)? They are supposed to be triggered by the approved status

Yes, if there is an approval and an update it requires to re-approve to trigger.

**Comment by KAUTH** [comment]
> > @MVrachev/@kairoaraujo how do we trigger the two last tests (DAS, Signed)? They are supposed to be triggered by the approved status
> 
> Yes, if there is an approval and an update it requires to re-approve to trigger.

Hm, I guess that's good, but sometimes it can be an issue since now I see that you also have to rebase or merge master to your branch before merging to master, so you need another approval, like currently 😄

**Comment by KAUTH** [comment]
@MVrachev I need a reapproval for the reason explained [above](https://github.com/repository-service-tuf/repository-service-tuf-cli/pull/430#issuecomment-1779549864) 😄

**Review by kairoaraujo — APPROVED** [review]

**Pull request merged**
