### PR TITLE
Feature/ux enhancement for options

### LINKED ISSUE #691: Other: CLI UX improvement
### What do you want to share with us?

We currently ask what is the Sigstore signing provider like this
```shell
> https://github.com/login/oauth
  https://login.microsoft.com
  https://accounts.google.com
```

We could use the names like:
```shell
> GitHub
  Google
  Microsoft
```

### References

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by mukulbindal**
# Description

This PR will show the names of the issuers, ie Google, GitHub, etc in place of the issuer URLs to the user. 

Fixes #691

# Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)

# Additional requirements
- [x] Tests have been added for the bug fix or new feature
- [ ] Docs have been added for the bug fix or new feature

# Code of Conduct
By submitting this PR, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.rst).

- [x] I agree to follow this project's Code of Conduct

### CODE REVIEW

**Comment by mukulbindal** [comment]
Hi @kairoaraujo Kindly review these changes for #691

**Review by kairoaraujo — APPROVED** [review]
Great work @mukulbindal !

**Comment by mukulbindal** [comment]
Thank you @kairoaraujo !!

**Comment by kairoaraujo** [comment]
@mukulbindal, if you have an interest in continuing to contribute to the RSTUF project, join us in the OpenSSF Channel 
https://repository-service-tuf.readthedocs.io/en/stable/#slack-channel

**Comment by mukulbindal** [comment]
Hi @kairoaraujo yes I am interested in contributing to RSTUF. Could you please help me signing up to slack, I don't see a sign up option :)

**Comment by kairoaraujo** [comment]
> Hi @kairoaraujo yes I am interested in contributing to RSTUF. Could you please help me signing up to slack, I don't see a sign up option :)

You can go to this page https://openssf.org/getinvolved/
There is a link Join our Slack"

**Pull request merged**
